//----------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool. Changes will be lost if the code is regenerated.
// </auto-generated>
//----------------------------------------------------------------------------------------
using System;
using System.Runtime.CompilerServices;

namespace VectorCore
{

    public readonly partial struct MatrixD4x4 : IFormattable
    {
        public readonly static MatrixD4x4 zero = new MatrixD4x4(
			0d, 0d, 0d, 0d,
			0d, 0d, 0d, 0d,
			0d, 0d, 0d, 0d,
			0d, 0d, 0d, 0d);
        public readonly static MatrixD4x4 identity = new MatrixD4x4(
			1d, 0d, 0d, 0d,
			0d, 1d, 0d, 0d,
			0d, 0d, 1d, 0d,
			0d, 0d, 0d, 1d);
    // File must be LF only or ToString will require CR removal: .Replace("\r", "")
    //public readonly string ToString(string format)=> $"{ m00.ToString(format)}, { m01.ToString(format)}, { m02.ToString(format)}, { m03.ToString(format)}, { m10.ToString(format)}, { m11.ToString(format)}, { m12.ToString(format)}, { m13.ToString(format)}, { m20.ToString(format)}, { m21.ToString(format)}, { m22.ToString(format)}, { m23.ToString(format)}, { m30.ToString(format)}, { m31.ToString(format)}, { m32.ToString(format)}, { m33.ToString(format)}";

        //public readonly override string ToString() => 
        //    @$"({CommonHelpers.ToStringWithDot(m00, "F2")}, {CommonHelpers.ToStringWithDot(m01, "F2")}, {CommonHelpers.ToStringWithDot(m02, "F2")}, {CommonHelpers.ToStringWithDot(m03, "F2")}, {CommonHelpers.ToStringWithDot(m10, "F2")}, {CommonHelpers.ToStringWithDot(m11, "F2")}, {CommonHelpers.ToStringWithDot(m12, "F2")}, {CommonHelpers.ToStringWithDot(m13, "F2")}, {CommonHelpers.ToStringWithDot(m20, "F2")}, {CommonHelpers.ToStringWithDot(m21, "F2")}, {CommonHelpers.ToStringWithDot(m22, "F2")}, {CommonHelpers.ToStringWithDot(m23, "F2")}, {CommonHelpers.ToStringWithDot(m30, "F2")}, {CommonHelpers.ToStringWithDot(m31, "F2")}, {CommonHelpers.ToStringWithDot(m32, "F2")}, {CommonHelpers.ToStringWithDot(m33, "F2")})";
    public readonly override string ToString() => 
            @$"{CommonHelpers.ToStringRound5WithDot(m00)}	{CommonHelpers.ToStringRound5WithDot(m01)}	{CommonHelpers.ToStringRound5WithDot(m02)}	{CommonHelpers.ToStringRound5WithDot(m03)}
{CommonHelpers.ToStringRound5WithDot(m10)}	{CommonHelpers.ToStringRound5WithDot(m11)}	{CommonHelpers.ToStringRound5WithDot(m12)}	{CommonHelpers.ToStringRound5WithDot(m13)}
{CommonHelpers.ToStringRound5WithDot(m20)}	{CommonHelpers.ToStringRound5WithDot(m21)}	{CommonHelpers.ToStringRound5WithDot(m22)}	{CommonHelpers.ToStringRound5WithDot(m23)}
{CommonHelpers.ToStringRound5WithDot(m30)}	{CommonHelpers.ToStringRound5WithDot(m31)}	{CommonHelpers.ToStringRound5WithDot(m32)}	{CommonHelpers.ToStringRound5WithDot(m33)}
".Replace("\r", "");
    public readonly string ToString(string format) => 
            @$"{CommonHelpers.ToStringWithDot(m00, format)}	{CommonHelpers.ToStringWithDot(m01, format)}	{CommonHelpers.ToStringWithDot(m02, format)}	{CommonHelpers.ToStringWithDot(m03, format)}
{CommonHelpers.ToStringWithDot(m10, format)}	{CommonHelpers.ToStringWithDot(m11, format)}	{CommonHelpers.ToStringWithDot(m12, format)}	{CommonHelpers.ToStringWithDot(m13, format)}
{CommonHelpers.ToStringWithDot(m20, format)}	{CommonHelpers.ToStringWithDot(m21, format)}	{CommonHelpers.ToStringWithDot(m22, format)}	{CommonHelpers.ToStringWithDot(m23, format)}
{CommonHelpers.ToStringWithDot(m30, format)}	{CommonHelpers.ToStringWithDot(m31, format)}	{CommonHelpers.ToStringWithDot(m32, format)}	{CommonHelpers.ToStringWithDot(m33, format)}
".Replace("\r", "");
    public readonly string ToString(string format, IFormatProvider formatProvider) => 
            @$"{CommonHelpers.ToStringWithDot(m00, format)}	{CommonHelpers.ToStringWithDot(m01, format)}	{CommonHelpers.ToStringWithDot(m02, format)}	{CommonHelpers.ToStringWithDot(m03, format)}
{CommonHelpers.ToStringWithDot(m10, format, formatProvider)}	{CommonHelpers.ToStringWithDot(m11, format, formatProvider)}	{CommonHelpers.ToStringWithDot(m12, format, formatProvider)}	{CommonHelpers.ToStringWithDot(m13, format, formatProvider)}
{CommonHelpers.ToStringWithDot(m20, format, formatProvider)}	{CommonHelpers.ToStringWithDot(m21, format, formatProvider)}	{CommonHelpers.ToStringWithDot(m22, format, formatProvider)}	{CommonHelpers.ToStringWithDot(m23, format, formatProvider)}
{CommonHelpers.ToStringWithDot(m30, format, formatProvider)}	{CommonHelpers.ToStringWithDot(m31, format, formatProvider)}	{CommonHelpers.ToStringWithDot(m32, format, formatProvider)}	{CommonHelpers.ToStringWithDot(m33, format, formatProvider)}
".Replace("\r", "");

    }
}