//----------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a _VectorLike_Constructor_Json.tt
//     Changes will be lost if the code is regenerated.
// </auto-generated>
//----------------------------------------------------------------------------------------
using Newtonsoft.Json;

namespace VectorCore
{
	[System.Serializable]	
    public readonly partial struct Vec2D
    {
		public readonly double x;
		public readonly double y;

		[JsonConstructor]
		public Vec2D(double x = 0d, double y = 0d)
		{
			this.x = x;
			this.y = y;
		}

		public void Deconstruct(out double x, out double y)
		{
			x = this.x;
			y = this.y;
		}
	}
}

