//----------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a _VectorLike_Constructor_Json.tt
//     Changes will be lost if the code is regenerated.
// </auto-generated>
//----------------------------------------------------------------------------------------
using Newtonsoft.Json;

namespace DoubleEngine
{
	[System.Serializable]	
    public readonly partial struct Vec2F
    {
		public readonly float x;
		public readonly float y;

		[JsonConstructor]
		public Vec2F(float x = 0f, float y = 0f)
		{
			this.x = x;
			this.y = y;
		}

		public void Deconstruct(out float x, out float y)
		{
			x = this.x;
			y = this.y;
		}
	}
}

