//----------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a _VectorLike_Constructor_Json.tt
//     Changes will be lost if the code is regenerated.
// </auto-generated>
//----------------------------------------------------------------------------------------
using Newtonsoft.Json;

namespace DoubleEngine
{
	[System.Serializable]	
    public readonly partial struct Vec3F
    {
		public readonly float x;
		public readonly float y;
		public readonly float z;

		[JsonConstructor]
		public Vec3F(float x = 0f, float y = 0f, float z = 0f)
		{
			this.x = x;
			this.y = y;
			this.z = z;
		}

		public void Deconstruct(out float x, out float y, out float z)
		{
			x = this.x;
			y = this.y;
			z = this.z;
		}
	}
}

