//----------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a _VectorLike_basicVectOperations.tt
//     Changes will be lost if the code is regenerated.
// </auto-generated>
//----------------------------------------------------------------------------------------

using System;
using System.Runtime.CompilerServices;

namespace DoubleEngine
{

public readonly partial struct Vec3F
{
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Vec3F operator +(in Vec3F lhs, in Vec3F r) => new Vec3F ( lhs.x + r.x, lhs.y + r.y, lhs.z + r.z );
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Vec3F AddVect(in Vec3F lhs, in Vec3F r) => new Vec3F ( lhs.x + r.x, lhs.y + r.y, lhs.z + r.z );
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public readonly Vec3F AddedVect(in Vec3F vector) => new Vec3F ( x + vector.x, y + vector.y, z + vector.z );

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Vec3F operator -(in Vec3F lhs, in Vec3F r) => new Vec3F ( lhs.x - r.x, lhs.y - r.y, lhs.z - r.z );
    
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Vec3F MultiplyVect(in Vec3F lhs, in Vec3F r) => new Vec3F ( lhs.x * r.x, lhs.y * r.y, lhs.z * r.z );
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public readonly Vec3F MultipliedVect(in Vec3F vector) => new Vec3F ( x * vector.x, y * vector.y, z * vector.z );
    

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Vec3F DivideVect(in Vec3F vector, in Vec3F divider) => new Vec3F ( vector.x / divider.x, vector.y / divider.y, vector.z / divider.z );
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public readonly Vec3F DividedByVect(in Vec3F divider) => new Vec3F ( x / divider.x, y / divider.y, z / divider.z );

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static Vec3F RemainderOfDivisionVect(in Vec3F vector, in Vec3F divider) => new Vec3F ( vector.x % divider.x, vector.y % divider.y, vector.z % divider.z );
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public readonly Vec3F RemainderOfDivisionVect(in Vec3F divider) => new Vec3F ( x % divider.x, y % divider.y, z % divider.z );

}

}
