//----------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a _VectorLike_Constructor_Json.tt
//     Changes will be lost if the code is regenerated.
// </auto-generated>
//----------------------------------------------------------------------------------------
using Newtonsoft.Json;

namespace DoubleEngine
{
	[System.Serializable]	
    public readonly partial struct Vec3D
    {
		public readonly double x;
		public readonly double y;
		public readonly double z;

		[JsonConstructor]
		public Vec3D(double x = 0d, double y = 0d, double z = 0d)
		{
			this.x = x;
			this.y = y;
			this.z = z;
		}

		public void Deconstruct(out double x, out double y, out double z)
		{
			x = this.x;
			y = this.y;
			z = this.z;
		}
	}
}

