//----------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a _Vector_IEquatable.tt
//     Changes will be lost if the code is regenerated.
// </auto-generated>
//----------------------------------------------------------------------------------------
using System;

namespace DoubleEngine
{
    public readonly partial struct Vec3F : IEquatable<Vec3F>
    {
        public readonly bool Equals(Vec3F other)
        {
			//return x == other.x && y == other.y && z == other.z;
            return SpecialEquality(this, other);
        }
        
        public static bool operator !=(in Vec3F lhs, in Vec3F rhs)=> !(lhs == rhs);
        public static bool operator ==(in Vec3F lhs, in Vec3F rhs)=> SpecialEquality(lhs, rhs);
		public static bool SpecialEquality(in Vec3F lhs, in Vec3F rhs)
        {
			double xDiff = lhs.x - rhs.x;
			double yDiff = lhs.y - rhs.y;
			double zDiff = lhs.z - rhs.z;
            return xDiff *xDiff + yDiff *yDiff + zDiff *zDiff<1e-26;
        }
        public readonly override int GetHashCode()
        {
            int hash = 5903;
			hash = ((hash << 5) ^ hash) ^ x.GetHashCode();
			hash = ((hash << 5) ^ hash) ^ y.GetHashCode();
			hash = ((hash << 5) ^ hash) ^ z.GetHashCode();
            return hash;
        }
        public readonly override bool Equals(object other)
        {
            if (!(other is Vec3F))
            {
                return false;
            }
            return Equals((Vec3F)other);
        }


    }
}

