//----------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Vec_ToFrom_Vectorlike.tt. 
//     Changes will be lost if the code is regenerated.
// </auto-generated>
//----------------------------------------------------------------------------------------
using System;

namespace VectorCore
{
    public readonly partial struct Vec3D : IConvertibleToOut<Vec3F>
    {
        public Vec3F ConvertTo(out Vec3F v)
        {
            Vec3F t = ToVec3F(this);
            v = t;
            return t;
        }
        public Vec3F ToVec3F() => ToVec3F(this);
        public static Vec3F ToVec3F(Vec3D d) => new Vec3F((float)d.x, (float)d.y, (float)d.z);
        public static Vec3D FromVec3F(Vec3F u) => new Vec3D(u.x, u.y, u.z);
        
        [Obsolete("use To or From Convertion method")]
        public static explicit operator Vec3F(Vec3D d) =>ToVec3F(d);
        [Obsolete("use To or From Convertion method")]
        public static explicit operator Vec3D(Vec3F u) => FromVec3F(u);
        
    }
}
