//----------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool. Changes will be lost if the code is regenerated.
// </auto-generated>
//----------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace DoubleEngine
{
    public static partial class VectorLike
    {
        public static Vec2D ConvertXYZtoXY(this Vec3D xyz) => new Vec2D(xyz.x, xyz.y);
        public static Vec3D ConvertXYtoXYZ(this Vec2D xy, double z = 0d) => new Vec3D(xy.x, xy.y, z);
    }
}
