//----------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool. Changes will be lost if the code is regenerated.
// </auto-generated>
//----------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace VectorCore
{
    public static partial class VectorLike
    {
		public static void Deconstruct( this Vec2D vectorLike, out double x, out double y)
		{
			x = vectorLike.x;
			y = vectorLike.y;
		}

		public static void Deconstruct( this Vec3D vectorLike, out double x, out double y, out double z)
		{
			x = vectorLike.x;
			y = vectorLike.y;
			z = vectorLike.z;
		}

		public static void Deconstruct( this Vec4D vectorLike, out double x, out double y, out double z, out double w)
		{
			x = vectorLike.x;
			y = vectorLike.y;
			z = vectorLike.z;
			w = vectorLike.w;
		}

		public static void Deconstruct( this QuaternionD vectorLike, out double x, out double y, out double z, out double w)
		{
			x = vectorLike.x;
			y = vectorLike.y;
			z = vectorLike.z;
			w = vectorLike.w;
		}

    }
}
